"""Fix: revert to declarative_base

Revision ID: 7c3197e783d3
Revises: cabcf96b7978
Create Date: 2025-05-02 23:22:50.878063

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7c3197e783d3"
down_revision: Union[str, None] = "cabcf96b7978"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
